<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
	</PropertyGroup>

	<ItemGroup>
		<!-- Core NUnit Testing Engine Stack -->
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.4" />
		<PackageReference Include="NUnit" Version="4.2.2" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.3.0" />

		<!-- Mocks and Database Assertions -->
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="FluentAssertions" Version="6.12.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
		<PackageReference Include="EntityFrameworkCore.Testing.Moq" Version="8.1.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ProductManagement.Api\ProductManagement.Api.csproj" />
	</ItemGroup>

</Project>
